import { useMemo, useRef, useState } from 'react';
import { Activity, ArrowUpRight, Bus, ChevronRight, Clock, Filter, RefreshCw, ShieldCheck, Sparkles, TriangleAlert } from 'lucide-react';
import { AreaChart, Area, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { DashboardData, UrbanEvent } from './types';
import { CityMap } from './components/CityMap';
import { CORRIDOR_LABEL } from './config/monitoredCorridor';
import type { LiveBusState } from './hooks/useLiveBuses';

const ago = (time: string) => time.replace('Today, ', '');
function Empty({ title }: { title: string }) { return <div className="empty"><Sparkles size={28}/><b>{title}</b><p>This view is ready for live FastAPI data.</p></div>; }
const alertLabel = (type: string) => type === 'Pothole' ? 'Pothole Detected' : type === 'Pedestrian safety' ? 'Pedestrian Safety Risk' : type;

export function Overview({ data, liveBuses, onSelect, onRunDemo, simulating, simulateError }: { data: DashboardData; liveBuses: LiveBusState; onSelect:(event:UrbanEvent)=>void; onRunDemo:(file: File)=>void; simulating?: boolean; simulateError?: string | null }) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const handleFile = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) onRunDemo(file);
    event.target.value = ''; // allow re-selecting the same file next time
  };
  const kpis = data.kpis.map((kpi, index) => index === 0 && liveBuses.isLive ? { ...kpi, value: String(liveBuses.buses?.length ?? 0), change: `${liveBuses.buses?.length ?? 0} live in corridor` } : kpi);
  return <>
    <div className="page-heading">
      <div><p className="eyebrow">MONITORED CORRIDOR · ±1% FLEXIBILITY</p><h1>Good morning, Hardik.</h1><p className="muted">Real-time intelligence for the defined Old Delhi–Badli corridor.</p></div>
      <button className="button primary" disabled={simulating} onClick={() => fileInputRef.current?.click()}>
        <Activity size={16}/> {simulating ? 'Processing video…' : 'Run live demo'}
      </button>
      <input ref={fileInputRef} type="file" accept="video/mp4,video/quicktime,video/x-msvideo" hidden onChange={handleFile}/>
    </div>
    {simulateError && <p className="muted" style={{ color: '#ef8d9b' }}>{simulateError}</p>}
    <div className="kpis">{kpis.map((kpi,index) => <div className="kpi" key={kpi.label}><div className={'kpi-icon '+kpi.tone}>{index===0?<Bus/>:index===1?<Activity/>:index===2?<TriangleAlert/>:<Clock/>}</div><div><small>{kpi.label}</small><h2>{kpi.value}</h2><p>{kpi.change}</p></div></div>)}</div>
    <div className="dashboard-grid">
      <section className="card map-card"><div className="card-title"><div><h3>Live corridor operations</h3><p>AI monitoring within the defined Old Delhi–Badli corridor</p></div><span className={'live '+(liveBuses.isLive ? '' : 'demo')}><i/> {liveBuses.isLive ? 'LIVE' : 'DEMO'}</span></div><CityMap compact events={data.events} buses={data.buses} liveBusState={liveBuses} onSelect={onSelect}/><div className="corridor-caption"><b>Monitored Corridor:</b> {CORRIDOR_LABEL}<small>Only areas within corridor boundary (±1%) are monitored.</small></div></section>
      <section className="card alerts"><div className="card-title"><div><h3>Priority alerts</h3><p>Within corridor only · demo AI feed</p></div><button className="text-button">View all <ChevronRight size={16}/></button></div>{data.events.slice(0,4).map((event) => <button className="alert-row" key={event.id} onClick={() => onSelect(event)}><i className={'severity '+event.severity}/><span><b>{alertLabel(event.type)}</b><small>{event.location} · {ago(event.timestamp)}</small></span><strong>{event.confidence}%</strong><ChevronRight size={16}/></button>)}</section>
      <section className="card traffic"><div className="card-title"><div><h3>Traffic flow</h3><p>Within corridor · demo traffic analytics</p></div><select><option>Today</option></select></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.traffic}><defs><linearGradient id="volume" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#36c7cf" stopOpacity=".45"/><stop offset="1" stopColor="#36c7cf" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="time" tickLine={false} axisLine={false} interval={0}/><YAxis hide/><Tooltip/><Area type="monotone" dataKey="volume" stroke="#36c7cf" strokeWidth={2} fill="url(#volume)"/></AreaChart></ResponsiveContainer></div></section>
      <section className="card fleet-summary"><div className="card-title"><div><h3>Fleet health</h3><p>{liveBuses.isLive ? 'Live OTD vehicles within corridor' : 'Demo fleet within corridor'}</p></div><ShieldCheck color="#4ed6aa"/></div>{liveBuses.isLive ? (liveBuses.buses?.length ? liveBuses.buses.map((bus) => <div className="fleet-row" key={bus.bus_id ?? `${bus.latitude}-${bus.longitude}`}><i/><span><b>{bus.label ?? bus.bus_id ?? 'Unlabelled bus'}</b><small>{bus.zone ?? 'Corridor connector'}</small></span><strong>{bus.speed === null ? '—' : bus.speed} <small>{bus.speed === null ? '' : 'km/h'}</small></strong></div>) : <div className="live-empty">No live buses currently inside the monitored corridor.</div>) : data.buses.map((bus) => <div className="fleet-row" key={bus.id}><i className={bus.status}/><span><b>{bus.id}</b><small>{bus.route}</small></span><strong>{bus.speed} <small>km/h</small></strong></div>)}</section>
    </div>
    <footer className="corridor-footer">All data, alerts, buses and cameras are limited to the monitored corridor. <span>{CORRIDOR_LABEL} · ±1% flexibility</span></footer>
  </>;
}

export function MapPage({ data, liveBuses, onSelect }: { data:DashboardData; liveBuses:LiveBusState; onSelect:(event:UrbanEvent)=>void }) { const [filters,setFilters] = useState<string[]>(['All']); const shown = filters.includes('All') ? data.events : data.events.filter((event) => filters.includes(event.type)); return <><div className="page-heading"><div><p className="eyebrow">GIS COMMAND MAP · MONITORED CORRIDOR</p><h1>Old Delhi–Badli spatial intelligence</h1><p className="muted">{CORRIDOR_LABEL} · only corridor zones (±1%) are shown.</p></div><button className="button"><RefreshCw size={15}/> Refresh feed</button></div><div className="map-layout"><aside className="filter-card"><h3><Filter size={16}/> Map layers</h3>{['All','Pothole','Traffic congestion','Infrastructure'].map((filter) => <label key={filter}><input type="checkbox" checked={filters.includes(filter)} onChange={() => setFilters((current) => current.includes(filter) ? current.filter((item) => item !== filter) : [...current.filter((item) => item !== 'All'),filter])}/><span>{filter}</span><small>{filter==='All'?data.events.length:data.events.filter((event) => event.type===filter).length}</small></label>)}<hr/><h3>Congestion overlay</h3><div className="heat"><i/><i/><i/><span>Low</span><span>High</span></div></aside><section className="card big-map"><CityMap events={shown} buses={data.buses} liveBusState={liveBuses} onSelect={onSelect}/></section></div></>; }

export function Listing({title,description,data,onSelect,filter}:{title:string;description:string;data:DashboardData;onSelect:(event:UrbanEvent)=>void;filter?:(event:UrbanEvent)=>boolean}) { const [query,setQuery]=useState(''); const events=useMemo(()=>data.events.filter((event)=>(!filter||filter(event))&&(`${event.id} ${event.type} ${event.location}`.toLowerCase().includes(query.toLowerCase()))),[data,filter,query]); return <><div className="page-heading"><div><p className="eyebrow">OPERATIONS QUEUE</p><h1>{title}</h1><p className="muted">{description}</p></div></div><section className="card table-card"><div className="table-toolbar"><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search event ID, type or location"/><button className="button"><Filter size={15}/> Filters</button></div>{events.length?<table><thead><tr><th>Event</th><th>Location</th><th>Confidence</th><th>Status</th><th>Detected</th><th/></tr></thead><tbody>{events.map((event)=><tr key={event.id} onClick={()=>onSelect(event)}><td><i className={'severity '+event.severity}/><b>{event.type}</b><small>{event.id} · {event.busId}</small></td><td>{event.location}</td><td>{event.confidence}%</td><td><span className={'status '+event.status}>{event.status}</span></td><td>{ago(event.timestamp)}</td><td><ArrowUpRight size={16}/></td></tr>)}</tbody></table>:<Empty title="No matching intelligence events"/>}</section></>; }
export function Placeholder({title}:{title:string}) { return <><div className="page-heading"><div><p className="eyebrow">URBAN INTELLIGENCE</p><h1>{title}</h1><p className="muted">This operational module is connected to the shared event service.</p></div></div><div className="card"><Empty title={`${title} dashboard`}/></div></>; }